const express=require('express')
const cors=require('cors')
const login = require('./routes/login')
const productos = require('./routes/productos')
const sucpro = require('./routes/sucpro')
const categorias = require('./routes/categorias')
const color = require('./routes/color')
const talla = require('./routes/talla')
const pagos = require('./routes/pagos')
const ventas = require('./routes/ventas')
const corte = require('./routes/corte')

const app=express()
app.listen(3030 || process.env.PORT,()=>{
    console.log('Servidor en puerto 3030')
})
app.use(express.json())
app.use(cors())

app.use('/login',login)
app.use('/productos',productos)
app.use('/sucpro',sucpro)
app.use('/categoria',categorias)
app.use('/color',color)
app.use('/talla',talla)
app.use('/pagos',pagos)
app.use('/ventas',ventas)
app.use('/corte',corte)
